name: Release

on:
  workflow_dispatch:
      inputs:
        tags:      
          description: 'Manually enter tag'
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Get Version
        id: get_version
        if: ${{ github.event_name == 'release' }}
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set version number
        if: ${{ github.event_name == 'release' }}
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ steps.get_version.outputs.VERSION }}"' ${{ github.workspace }}/custom_components/keymaster_lite/const.py
          sed -i '/version/c\  \"version\": \"${{ steps.get_version.outputs.VERSION }}\"' ${{ github.workspace }}/custom_components/keymaster_lite/manifest.json
      - name: Set version number
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          sed -i '/VERSION = /c\VERSION = "${{inputs.tags}}"' ${{ github.workspace }}/custom_components/keymaster_lite/const.py
          sed -i '/version/c\  \"version\": \"${{inputs.tags}}\"' ${{ github.workspace }}/custom_components/keymaster_lite/manifest.json
      # Pack the keymaster_lite dir as a zip and upload to the release
      - name: ZIP keymaster_lite Dir
        run: |
          cd ${{ github.workspace }}/custom_components/keymaster_lite
          zip keymaster_lite.zip -r ./
      - name: 📤 Upload zip to release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/keymaster_lite/keymaster_lite.zip
      - name: 📤 Upload zip to release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/keymaster_lite/keymaster_lite.zip
          tag_name: ${{inputs.tags}}
